vezetéknév = input('Mi a vezetékneved? ')
keresztnév = input('Mi a keresztneved? ')
év = input('Melyik évben születtél? ')
csillagjegy = input('Melyik csillagjegyben születtél? ')
print('A te neved ', vezetéknév, ' ', keresztnév,'.', sep='')
print('Az Úr ', év, '. évben született, a ', csillagjegy , 'jegyben.', sep='')